from pathlib import Path
p=Path('index.html'); s=p.read_text()
s=s.replace('>AGENDAR PRIMEIRA AULA</a>\n        <a class="btn btn-ghost" href="#classico">CONHECER O MÉTODO</a>','>QUERO CONHECER A NOREMATI</a>\n        <a class="btn btn-ghost" href="#classico">CONHECER O MÉTODO</a>',1)
s=s.replace('<div class="first-lesson-action reveal"><a class="btn" href="https://wa.me/5511981346510" data-booking-open>AGENDAR PRIMEIRA AULA</a></div>','<div class="first-lesson-action reveal"><a class="btn" href="https://wa.me/5511981346510" data-booking-open>CONVERSAR COM A FABIANA</a></div>')
trust='''<section class="conversion-trust" aria-label="Por que escolher a Noremati"><div class="wrap"><div class="section-center reveal"><div class="eyebrow">Confiança para começar</div><h2>Tradição, experiência e atenção a cada aluno.</h2><p>Na Noremati, sua prática une a essência do Pilates Clássico a um acompanhamento próximo, em um ambiente pensado para evoluir com segurança e consistência.</p></div><div class="trust-grid"><div class="trust-item reveal"><strong>+15 anos</strong><span>de experiência profissional</span></div><div class="trust-item reveal"><strong>Linhagem clássica</strong><span>Joseph → Romana → Inelia → Fabiana</span></div><div class="trust-item reveal"><strong>Personalizado</strong><span>atenção ao seu momento e objetivos</span></div><div class="trust-item reveal"><strong>Santos · SP</strong><span>atendimento na Ponta da Praia</span></div></div></div></section>\n'''
s=s.replace('<section class="faq" id="faq">',trust+'<section class="faq" id="faq">')
a=s.index('<form id="bookingForm"'); b=s.index('</form>',a)+7
form='''<form id="bookingForm" class="booking-form" novalidate><div class="booking-field"><label for="bookingNome">Como podemos te chamar?</label><input type="text" id="bookingNome" name="nome" autocomplete="given-name" placeholder="Seu nome" required><span class="booking-error" data-error-for="bookingNome"></span></div><div class="booking-field"><label for="bookingObjetivo">O que você busca neste momento?</label><select id="bookingObjetivo" name="objetivo" required><option value="">Selecione uma opção</option><option>Quero começar Pilates</option><option>Quero melhorar força e mobilidade</option><option>Quero conhecer o Pilates Clássico</option><option>Tenho uma necessidade específica</option></select><span class="booking-error" data-error-for="bookingObjetivo"></span></div><button class="booking-btn primary" type="submit">Conversar com a Fabiana no WhatsApp</button></form>'''
s=s[:a]+form+s[b:]
s=s.replace('Preencha seus dados e continue direto no WhatsApp para combinar o melhor horário com a Noremati.','Conte rapidamente o que você procura. A conversa continua direto no WhatsApp com a Fabiana, sem compromisso.')
s=s.replace("  const sobrenomeInput = document.getElementById('bookingSobrenome');\n  const telInput = document.getElementById('bookingTelefone');","  const objetivoInput = document.getElementById('bookingObjetivo');")
a=s.index('  // Máscara de telefone brasileiro:'); b=s.index("  form.addEventListener('submit'",a); s=s[:a]+s[b:]
a=s.index("  form.addEventListener('submit', function(e){"); b=s.index("  document.querySelectorAll('.booking-btn.secondary",a)
js='''  form.addEventListener('submit', function(e){ e.preventDefault(); let valid=true; if(nomeInput.value.trim().length<2){setError(nomeInput,'Informe seu nome.');valid=false}else setError(nomeInput,''); if(!objetivoInput.value){setError(objetivoInput,'Selecione o que você busca.');valid=false}else setError(objetivoInput,''); if(!valid)return; const mensagem='Olá, Fabiana! Meu nome é '+nomeInput.value.trim()+'. Conheci a Noremati pelo site e gostaria de conversar sobre Pilates Clássico.\\n\\n*Meu objetivo:* '+objetivoInput.value+'\\n\\nPodemos conversar sobre a primeira aula?'; const url='https://wa.me/5511981346510?text='+encodeURIComponent(mensagem); if(typeof gtag==='function')gtag('event','generate_lead',{method:'whatsapp',objective:objetivoInput.value}); window.open(url,'_blank','noopener'); closeModal(); form.reset(); });\n\n'''
s=s[:a]+js+s[b:]
css='''\n/* Conversion journey */\n.conversion-trust{background:#fffaf1;padding:76px 0}.trust-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:18px}.trust-item{padding:24px 20px;border-top:1px solid var(--gold2);background:rgba(255,255,255,.38)}.trust-item strong{display:block;font-family:"Cormorant Garamond",serif;font-size:28px;line-height:1;color:var(--ink);margin-bottom:8px}.trust-item span{font-size:13px;line-height:1.45;color:var(--muted)}.booking-field select{width:100%;padding:14px;border:1px solid var(--line);border-radius:12px;background:#fff;color:var(--ink);font:inherit}@media(max-width:900px){.trust-grid{grid-template-columns:1fr 1fr}}@media(max-width:620px){.conversion-trust{padding:60px 0}.trust-grid{grid-template-columns:1fr}}\n'''
s=s.replace('</style>',css+'</style>')
p.write_text(s)
